version: 2
jobs:
  build:
    working_directory: ~/example-foobar
    docker:
      - image: ruby:2.4
        environment:
          CODECLIMATE_REPO_TOKEN: "fa28857f9940405b0eacaf164ea6cc54c216fb44e8d4a0b479240e7cf344fe0f"
    steps:
      - checkout
      - type: cache-restore
        key: example-foobar-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: example-foobar-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec rspec && bundle exec codeclimate-test-reporter
