version: 2
jobs:
  build:
    working_directory: ~/example-foobar
    docker:
      - image: ruby:2.4
        environment:
          CC_TEST_REPORTER_ID: "cfc69029593bbb14f78212a6d4b3f8b8268f323b8cc2134ca30bc37fd89a463d"
    steps:
      - checkout
      - type: cache-restore
        key: example-foobar-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: example-foobar-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec
            ./cc-test-reporter after-build
